import { createPublicClient, http } from 'viem';
import fs from 'node:fs';
const { address, abi } = JSON.parse(fs.readFileSync('src/lib/ritual/contract.json','utf8'));
const pc = createPublicClient({ transport: http('https://rpc.ritualfoundation.org') });
const uri = await pc.readContract({address,abi,functionName:'tokenURI',args:[1n]});
console.log('prefix25:', JSON.stringify(uri.slice(0,60)));
const b64 = uri.slice('data:application/json;base64,'.length);
console.log('b64 first80:', JSON.stringify(b64.slice(0,80)));
const raw = Buffer.from(b64,'base64');
console.log('raw first80 hex:', raw.slice(0,80).toString('hex'));
console.log('raw first80 utf8:', JSON.stringify(raw.slice(0,80).toString('utf8')));
